<a href="https://colab.research.google.com/github/teemus28/Machine-Learning/blob/main/Library1_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dict1 = {"name":['sumeet','rohan','rohit','manoj'],
         "branch":['EE','chem','ECE','cs'],
         "CPI":[9.12,8.73,7.79,6.25]
}

In [ ]:
df = pd.DataFrame(dict1)

In [ ]:
df

     name branch   CPI
0  sumeet     EE  9.12
1   rohan   chem  8.73
2   rohit    ECE  7.79
3   manoj     cs  6.25

In [ ]:
df.to_csv("friends.csv")   #convert data to csvfile

In [ ]:
df.to_csv("friends_index_false.csv",index=False) #remove 1st column

In [ ]:
df.head(2)

     name branch   CPI
0  sumeet     EE  9.12
1   rohan   chem  8.73

In [ ]:
df.tail(2)

    name branch   CPI
2  rohit    ECE  7.79
3  manoj     cs  6.25

In [ ]:
df.describe()

            CPI
count  4.000000
mean   7.972500
std    1.276829
min    6.250000
25%    7.405000
50%    8.260000
75%    8.827500
max    9.120000

In [ ]:
details=pd.read_excel("/content/details.csv.xlsx")

In [ ]:
details

   Sno.    NAME branch   CPI
0     0  sumeet     EE  9.12
1     1   rohan   chem  8.73
2     2   rohit    ECE  7.79
3     3   manoj     cs  6.25

In [ ]:
df

     name branch   CPI
0  sumeet     EE  9.12
1   rohan   chem  8.73
2   rohit    ECE  7.79
3   manoj     cs  6.25

In [ ]:
df['CPI'][0]=9.45

<ipython-input-24-5cca6dde3779>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CPI'][0]=9.45

In [ ]:
df

     name branch   CPI
0  sumeet     EE  9.45
1   rohan   chem  8.73
2   rohit    ECE  7.79
3   manoj     cs  6.25

In [ ]:
df.index=['first','second','third','fourth']

In [ ]:
df

          name branch   CPI
first   sumeet     EE  9.45
second   rohan   chem  8.73
third    rohit    ECE  7.79
fourth   manoj     cs  6.25

In [ ]:
details['CPI'][0]=9.45

<ipython-input-28-39ea1de2111d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details['CPI'][0]=9.45

In [ ]:
details

   Sno.    NAME branch   CPI
0     0  sumeet     EE  9.45
1     1   rohan   chem  8.73
2     2   rohit    ECE  7.79
3     3   manoj     cs  6.25

In [ ]:
details.index=['first','second','third','fourth']

In [ ]:
details

        Sno.    NAME branch   CPI
first      0  sumeet     EE  9.45
second     1   rohan   chem  8.73
third      2   rohit    ECE  7.79
fourth     3   manoj     cs  6.25

In [ ]:
df

          name branch   CPI
first   sumeet     EE  9.45
second   rohan   chem  8.73
third    rohit    ECE  7.79
fourth   manoj     cs  6.25

In [ ]:
col=df['name']
col

first     sumeet
second     rohan
third      rohit
fourth     manoj
Name: name, dtype: object

In [ ]:
col1=pd.Series(col)

In [ ]:
col1

first     sumeet
second     rohan
third      rohit
fourth     manoj
Name: name, dtype: object

In [ ]:
sr=pd.Series(np.random.rand(25))  #0-1 ,25 values

In [ ]:
sr

0     0.176513
1     0.703356
2     0.365612
3     0.767155
4     0.846040
5     0.167622
6     0.983239
7     0.645246
8     0.540566
9     0.781343
10    0.047093
11    0.494579
12    0.248103
13    0.254631
14    0.214383
15    0.409331
16    0.353073
17    0.636790
18    0.877557
19    0.086651
20    0.281358
21    0.756166
22    0.339725
23    0.409368
24    0.560086
dtype: float64

In [ ]:
df_2=pd.DataFrame(np.random.rand(233,5),index=np.arange(233))

In [ ]:
df_2

            0         1         2         3         4
0    0.505724  0.977317  0.620266  0.346546  0.418568
1    0.238900  0.778941  0.616654  0.709412  0.299857
2    0.215291  0.824261  0.940882  0.924560  0.226349
3    0.507420  0.878838  0.958144  0.558081  0.726790
4    0.959428  0.143265  0.926074  0.236484  0.947713
..        ...       ...       ...       ...       ...
228  0.626046  0.068364  0.846012  0.499251  0.384652
229  0.722078  0.369965  0.206515  0.418567  0.972182
230  0.125202  0.233600  0.598401  0.417948  0.080108
231  0.769005  0.991114  0.932907  0.171091  0.565080
232  0.833519  0.345249  0.745826  0.023201  0.987919

[233 rows x 5 columns]

In [ ]:
type(df_2)

pandas.core.frame.DataFrame

In [ ]:
type(sr)

pandas.core.series.Series

In [ ]:
df_2[0][1]="sumeet"

In [ ]:
df_2

            0         1         2         3         4
0    0.505724  0.977317  0.620266  0.346546  0.418568
1      sumeet  0.778941  0.616654  0.709412  0.299857
2    0.215291  0.824261  0.940882  0.924560  0.226349
3     0.50742  0.878838  0.958144  0.558081  0.726790
4    0.959428  0.143265  0.926074  0.236484  0.947713
..        ...       ...       ...       ...       ...
228  0.626046  0.068364  0.846012  0.499251  0.384652
229  0.722078  0.369965  0.206515  0.418567  0.972182
230  0.125202  0.233600  0.598401  0.417948  0.080108
231  0.769005  0.991114  0.932907  0.171091  0.565080
232  0.833519  0.345249  0.745826  0.023201  0.987919

[233 rows x 5 columns]

In [ ]:
df_2.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       223, 224, 225, 226, 227, 228, 229, 230, 231, 232],
      dtype='int64', length=233)

In [ ]:
df_2.columns

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df_2.to_numpy()    #convert df to numpy array

array([[0.5057235601773451, 0.9773168511784162, 0.620266000906338,
        0.34654598699694883, 0.4185679323323691],
       ['sumeet', 0.7789413846518402, 0.6166537465971931,
        0.7094119033056059, 0.29985684812621294],
       [0.21529074423519434, 0.8242607562917915, 0.940882194028395,
        0.9245600954464389, 0.2263493598331905],
       ...,
       [0.1252020405960389, 0.23360025883047242, 0.5984006989274413,
        0.41794766114665016, 0.08010789920662453],
       [0.7690047339418968, 0.9911137893152862, 0.9329065954605401,
        0.17109140577210158, 0.5650799827373517],
       [0.8335193523248036, 0.3452492894043958, 0.7458264693261664,
        0.023200578113878545, 0.9879187506153965]], dtype=object)

In [ ]:
df_2.T   #transpose df i.e. rows becomes columns

,0,1,2,3,4,5,6,7,8,9,...,223,224,225,226,227,228,229,230,231,232
0,0.505724,sumeet,0.215291,0.50742,0.959428,0.454225,0.48855,0.455991,0.159648,0.587525,...,0.998911,0.878218,0.968563,0.163102,0.507879,0.626046,0.722078,0.125202,0.769005,0.833519
1,0.977317,0.778941,0.824261,0.878838,0.143265,0.631777,0.561101,0.036007,0.703957,0.106393,...,0.746941,0.042916,0.754095,0.000876,0.947682,0.068364,0.369965,0.2336,0.991114,0.345249
2,0.620266,0.616654,0.940882,0.958144,0.926074,0.771405,0.927494,0.553789,0.475705,0.831995,...,0.949525,0.439779,0.283713,0.906788,0.2917,0.846012,0.206515,0.598401,0.932907,0.745826
3,0.346546,0.709412,0.92456,0.558081,0.236484,0.463645,0.687472,0.111017,0.988921,0.014998,...,0.112318,0.014576,0.402674,0.307321,0.766463,0.499251,0.418567,0.417948,0.171091,0.023201
4,0.418568,0.299857,0.226349,0.72679,0.947713,0.425364,0.043049,0.072886,0.835754,0.981382,...,0.970326,0.94027,0.611969,0.94236,0.087574,0.384652,0.972182,0.080108,0.56508,0.987919

In [ ]:
df_2.head()

          0         1         2         3         4
0  0.505724  0.977317  0.620266  0.346546  0.418568
1    sumeet  0.778941  0.616654  0.709412  0.299857
2  0.215291  0.824261  0.940882  0.924560  0.226349
3   0.50742  0.878838  0.958144  0.558081  0.726790
4  0.959428  0.143265  0.926074  0.236484  0.947713

In [ ]:
df_2.sort_index(axis=0,ascending=False)
# axis =0 for sorting rows , axis=1 for sorting columns
#bydefault ascending , so we change it
#sort wrt index

            0         1         2         3         4
232  0.833519  0.345249  0.745826  0.023201  0.987919
231  0.769005  0.991114  0.932907  0.171091  0.565080
230  0.125202  0.233600  0.598401  0.417948  0.080108
229  0.722078  0.369965  0.206515  0.418567  0.972182
228  0.626046  0.068364  0.846012  0.499251  0.384652
..        ...       ...       ...       ...       ...
4    0.959428  0.143265  0.926074  0.236484  0.947713
3     0.50742  0.878838  0.958144  0.558081  0.726790
2    0.215291  0.824261  0.940882  0.924560  0.226349
1      sumeet  0.778941  0.616654  0.709412  0.299857
0    0.505724  0.977317  0.620266  0.346546  0.418568

[233 rows x 5 columns]

In [ ]:
df_2[0].head()

0    0.505724
1      sumeet
2    0.215291
3     0.50742
4    0.959428
Name: 0, dtype: object

In [ ]:
type(df_2[0])

pandas.core.series.Series

In [ ]:
# df_2_new=df_2   #not copy , only for showing
# df_2_new=df_2.copy()  #copy

In [ ]:
df_2.head()

          0         1         2         3         4
0  0.505724  0.977317  0.620266  0.346546  0.418568
1    sumeet  0.778941  0.616654  0.709412  0.299857
2  0.215291  0.824261  0.940882  0.924560  0.226349
3   0.50742  0.878838  0.958144  0.558081  0.726790
4  0.959428  0.143265  0.926074  0.236484  0.947713

In [ ]:
df_2.loc[0,3]=9

In [ ]:
df_2.head()

          0         1         2         3         4
0  0.505724  0.977317  0.620266  9.000000  0.418568
1    sumeet  0.778941  0.616654  0.709412  0.299857
2  0.215291  0.824261  0.940882  0.924560  0.226349
3   0.50742  0.878838  0.958144  0.558081  0.726790
4  0.959428  0.143265  0.926074  0.236484  0.947713

In [ ]:
df_2.columns=list("ABCDE")

In [ ]:
df_2.head()

          A         B         C         D         E
0  0.505724  0.977317  0.620266  9.000000  0.418568
1    sumeet  0.778941  0.616654  0.709412  0.299857
2  0.215291  0.824261  0.940882  0.924560  0.226349
3   0.50742  0.878838  0.958144  0.558081  0.726790
4  0.959428  0.143265  0.926074  0.236484  0.947713

In [ ]:
df_2.loc[0,'A']=98

In [ ]:
df_2.head()

          A         B         C         D         E
0        98  0.977317  0.620266  9.000000  0.418568
1    sumeet  0.778941  0.616654  0.709412  0.299857
2  0.215291  0.824261  0.940882  0.924560  0.226349
3   0.50742  0.878838  0.958144  0.558081  0.726790
4  0.959428  0.143265  0.926074  0.236484  0.947713

In [ ]:
df_2.loc[0,0]=54

In [ ]:
df_2.head()

          A         B         C         D         E     0
0        98  0.977317  0.620266  9.000000  0.418568  54.0
1    sumeet  0.778941  0.616654  0.709412  0.299857   NaN
2  0.215291  0.824261  0.940882  0.924560  0.226349   NaN
3   0.50742  0.878838  0.958144  0.558081  0.726790   NaN
4  0.959428  0.143265  0.926074  0.236484  0.947713   NaN

In [ ]:
df_2.drop(0,axis=1).head()

          A         B         C         D         E
0        98  0.977317  0.620266  9.000000  0.418568
1    sumeet  0.778941  0.616654  0.709412  0.299857
2  0.215291  0.824261  0.940882  0.924560  0.226349
3   0.50742  0.878838  0.958144  0.558081  0.726790
4  0.959428  0.143265  0.926074  0.236484  0.947713

In [ ]:
df_2.drop('A',axis=1)

            B         C         D         E     0
0    0.977317  0.620266  9.000000  0.418568  54.0
1    0.778941  0.616654  0.709412  0.299857   NaN
2    0.824261  0.940882  0.924560  0.226349   NaN
3    0.878838  0.958144  0.558081  0.726790   NaN
4    0.143265  0.926074  0.236484  0.947713   NaN
..        ...       ...       ...       ...   ...
228  0.068364  0.846012  0.499251  0.384652   NaN
229  0.369965  0.206515  0.418567  0.972182   NaN
230  0.233600  0.598401  0.417948  0.080108   NaN
231  0.991114  0.932907  0.171091  0.565080   NaN
232  0.345249  0.745826  0.023201  0.987919   NaN

[233 rows x 5 columns]

In [ ]:
df_2.loc[[0,3],['A','B','C']]

         A     B         C
0       98  None  0.620266
3  0.50742  None  0.958144

In [ ]:
df_2.loc[:,['A','C']]

            A         C
0          98  0.620266
1      sumeet  0.616654
2    0.215291  0.940882
3     0.50742  0.958144
4    0.959428  0.926074
..        ...       ...
228  0.626046  0.846012
229  0.722078  0.206515
230  0.125202  0.598401
231  0.769005  0.932907
232  0.833519  0.745826

[233 rows x 2 columns]

In [ ]:
df_2.loc[[0,3],:]

         A         B         C         D         E     0
0       98  0.977317  0.620266  9.000000  0.418568  54.0
3  0.50742  0.878838  0.958144  0.558081  0.726790   NaN

In [ ]:
df_2.loc[(df_2['B']<0.3) & (df_2['C']>0.1)]     #condn/s on loc

            A         B         C         D         E   0
4    0.959428  0.143265  0.926074  0.236484  0.947713 NaN
7    0.455991  0.036007  0.553789  0.111017  0.072886 NaN
9    0.587525  0.106393  0.831995  0.014998  0.981382 NaN
10   0.251324  0.103403  0.732742  0.922799  0.407732 NaN
12   0.290677  0.107134  0.681248  0.696385  0.548403 NaN
..        ...       ...       ...       ...       ...  ..
217  0.845255  0.017628  0.980202  0.045788  0.035263 NaN
224  0.878218  0.042916  0.439779  0.014576  0.940270 NaN
226  0.163102  0.000876  0.906788  0.307321  0.942360 NaN
228  0.626046  0.068364  0.846012  0.499251  0.384652 NaN
230  0.125202  0.233600  0.598401  0.417948  0.080108 NaN

[67 rows x 6 columns]

In [ ]:
#we can select on the basis of "names" rows and columns of df by loc

In [ ]:
df_2.iloc[:,0:3]

            A         B         C
0          98  0.977317  0.620266
1      sumeet  0.778941  0.616654
2    0.215291  0.824261  0.940882
3     0.50742  0.878838  0.958144
4    0.959428  0.143265  0.926074
..        ...       ...       ...
228  0.626046  0.068364  0.846012
229  0.722078  0.369965  0.206515
230  0.125202  0.233600  0.598401
231  0.769005  0.991114  0.932907
232  0.833519  0.345249  0.745826

[233 rows x 3 columns]

In [ ]:
df_2.iloc[[0,1],[0,2]]

        A         C
0      98  0.620266
1  sumeet  0.616654

In [ ]:
df_2.iloc[:,1]=None  #change values of df
df_2

            A     B         C         D         E     0
0          98  None  0.620266  9.000000  0.418568  54.0
1      sumeet  None  0.616654  0.709412  0.299857   NaN
2    0.215291  None  0.940882  0.924560  0.226349   NaN
3     0.50742  None  0.958144  0.558081  0.726790   NaN
4    0.959428  None  0.926074  0.236484  0.947713   NaN
..        ...   ...       ...       ...       ...   ...
228  0.626046  None  0.846012  0.499251  0.384652   NaN
229  0.722078  None  0.206515  0.418567  0.972182   NaN
230  0.125202  None  0.598401  0.417948  0.080108   NaN
231  0.769005  None  0.932907  0.171091  0.565080   NaN
232  0.833519  None  0.745826  0.023201  0.987919   NaN

[233 rows x 6 columns]

In [ ]:
df_2.drop([0])   #drop 1st row

            A     B         C         D         E   0
1      sumeet  None  0.616654  0.709412  0.299857 NaN
2    0.215291  None  0.940882  0.924560  0.226349 NaN
3     0.50742  None  0.958144  0.558081  0.726790 NaN
4    0.959428  None  0.926074  0.236484  0.947713 NaN
5    0.454225  None  0.771405  0.463645  0.425364 NaN
..        ...   ...       ...       ...       ...  ..
228  0.626046  None  0.846012  0.499251  0.384652 NaN
229  0.722078  None  0.206515  0.418567  0.972182 NaN
230  0.125202  None  0.598401  0.417948  0.080108 NaN
231  0.769005  None  0.932907  0.171091  0.565080 NaN
232  0.833519  None  0.745826  0.023201  0.987919 NaN

[232 rows x 6 columns]

In [ ]:
#df_2.drop(['A','C'], axis=1)  #drop 1st col
#it returns a copy

In [ ]:
#df_2=df_2.drop(['A','C'], axis=1)
#it changes main df

In [ ]:
#df_2.drop(['A','C'], axis=1, inplace=True) #it changes main df

In [ ]:
df_2.head()

          A     B         C         D         E     0
0        98  None  0.620266  9.000000  0.418568  54.0
1    sumeet  None  0.616654  0.709412  0.299857   NaN
2  0.215291  None  0.940882  0.924560  0.226349   NaN
3   0.50742  None  0.958144  0.558081  0.726790   NaN
4  0.959428  None  0.926074  0.236484  0.947713   NaN

In [ ]:
df_2.drop([0,4])  #drop row no.0 and 4

            A     B         C         D         E   0
1      sumeet  None  0.616654  0.709412  0.299857 NaN
2    0.215291  None  0.940882  0.924560  0.226349 NaN
3     0.50742  None  0.958144  0.558081  0.726790 NaN
5    0.454225  None  0.771405  0.463645  0.425364 NaN
6     0.48855  None  0.927494  0.687472  0.043049 NaN
..        ...   ...       ...       ...       ...  ..
228  0.626046  None  0.846012  0.499251  0.384652 NaN
229  0.722078  None  0.206515  0.418567  0.972182 NaN
230  0.125202  None  0.598401  0.417948  0.080108 NaN
231  0.769005  None  0.932907  0.171091  0.565080 NaN
232  0.833519  None  0.745826  0.023201  0.987919 NaN

[231 rows x 6 columns]

In [ ]:
df_2.head()

          A     B         C         D         E     0
0        98  None  0.620266  9.000000  0.418568  54.0
1    sumeet  None  0.616654  0.709412  0.299857   NaN
2  0.215291  None  0.940882  0.924560  0.226349   NaN
3   0.50742  None  0.958144  0.558081  0.726790   NaN
4  0.959428  None  0.926074  0.236484  0.947713   NaN

In [ ]:
df_2.reset_index()  #andd index column of 0-columns

     index         A     B         C         D         E     0
0        0        98  None  0.620266  9.000000  0.418568  54.0
1        1    sumeet  None  0.616654  0.709412  0.299857   NaN
2        2  0.215291  None  0.940882  0.924560  0.226349   NaN
3        3   0.50742  None  0.958144  0.558081  0.726790   NaN
4        4  0.959428  None  0.926074  0.236484  0.947713   NaN
..     ...       ...   ...       ...       ...       ...   ...
228    228  0.626046  None  0.846012  0.499251  0.384652   NaN
229    229  0.722078  None  0.206515  0.418567  0.972182   NaN
230    230  0.125202  None  0.598401  0.417948  0.080108   NaN
231    231  0.769005  None  0.932907  0.171091  0.565080   NaN
232    232  0.833519  None  0.745826  0.023201  0.987919   NaN

[233 rows x 7 columns]

In [ ]:
df_2.reset_index(drop=True)# it add index on existing col

            A     B         C         D         E     0
0          98  None  0.620266  9.000000  0.418568  54.0
1      sumeet  None  0.616654  0.709412  0.299857   NaN
2    0.215291  None  0.940882  0.924560  0.226349   NaN
3     0.50742  None  0.958144  0.558081  0.726790   NaN
4    0.959428  None  0.926074  0.236484  0.947713   NaN
..        ...   ...       ...       ...       ...   ...
228  0.626046  None  0.846012  0.499251  0.384652   NaN
229  0.722078  None  0.206515  0.418567  0.972182   NaN
230  0.125202  None  0.598401  0.417948  0.080108   NaN
231  0.769005  None  0.932907  0.171091  0.565080   NaN
232  0.833519  None  0.745826  0.023201  0.987919   NaN

[233 rows x 6 columns]

In [ ]:
#dropna in pandas

In [ ]:
#drop duplicates in pandas

In [ ]:
df.shape

(4, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, first to fourth
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   branch  4 non-null      object
 2   CPI     4 non-null      float64
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [ ]:
df.head()

          name branch   CPI
first   sumeet     EE  9.45
second   rohan   chem  8.73
third    rohit    ECE  7.79
fourth   manoj     cs  6.25

In [ ]:
df['branch'].value_counts(dropna=False)

branch
EE      1
chem    1
ECE     1
cs      1
Name: count, dtype: int64

In [ ]:
df.notnull()  #false at null values

        name  branch   CPI
first   True    True  True
second  True    True  True
third   True    True  True
fourth  True    True  True

In [ ]:
df.isnull()

         name  branch    CPI
first   False   False  False
second  False   False  False
third   False   False  False
fourth  False   False  False

In [ ]:
#mean , corr , count , max , min , median , std

In [ ]:
df.head()

          name branch   CPI
first   sumeet     EE  9.45
second   rohan   chem  8.73
third    rohit    ECE  7.79
fourth   manoj     cs  6.25

In [ ]:
for x in df.index:
  if df["CPI"].loc[x] > 9:
    df["CPI"].loc[x] = 8.5

In [ ]:
df

          name branch   CPI
first   sumeet     EE  8.50
second   rohan   chem  8.73
third    rohit    ECE  7.79
fourth   manoj     cs  6.25

In [ ]:
df = df.iloc[:,]

In [ ]:
df

       branch   CPI
first      EE  8.50
second   chem  8.73
third     ECE  7.79
fourth     cs  6.25

In [ ]:
Df = pd.read_csv("/content/data.csv")

In [ ]:
Df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
Df.corr()

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000